dbtdemo:
  outputs:
    dev:
      account: gp53418.us-east-2.aws
      database: airbnb
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 4
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev

dbt_postgres:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5431
      user: postgres
      pass: mypass
      dbname: postgres
      schema: dbo
  target: dev

dbt_sqlserver:
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      port: 1431
      schema: dbo
      user: SA
      password: Pass@123456
      database: master
  target: dev